# Generated by Django 5.0.4 on 2024-04-25 08:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="TR"
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(max_length=255, verbose_name="Neighborhood"),
                ),
                ("street", models.CharField(max_length=50, verbose_name="Street")),
                (
                    "building_number",
                    models.CharField(max_length=50, verbose_name="Building Number"),
                ),
                ("zip_code", models.CharField(max_length=5, verbose_name="Zip Code")),
                ("district", models.CharField(max_length=50, verbose_name="District")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "address_detail",
                    models.TextField(
                        blank=True, null=True, verbose_name="Address Detail"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
