# Generated by Django 5.0.4 on 2024-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[("CUSTOMER", "CUSTOMER"), ("BUSINESS", "BUSINESS")],
                default="CUSTOMER",
                verbose_name="Account Type",
            ),
        ),
    ]
