# Generated by Django 5.0.4 on 2024-04-24 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Business Name"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="businesses/default.jpg",
                        upload_to="businesses",
                        verbose_name="Business Image",
                    ),
                ),
                (
                    "minimum_basket_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Minimum Basket Amount",
                    ),
                ),
                ("address", models.TextField(verbose_name="Business Address")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
            },
        ),
    ]
